// @generated by scripts/generate-backup-schema-refs.ts — DO NOT EDIT
//
// Auto-generated from src/main/data/db/schemas/*.ts via Drizzle runtime reflection.
// Regenerate: pnpm backup:refs:generate · Verify (CI-enforced): pnpm backup:refs:check.
// Do NOT edit by hand — change the Drizzle schemas and re-run the generator.

// Table/column identifier types (main-only neutral layer). These are literal unions
// derived from DB_TABLES / DB_COLUMNS_BY_TABLE, not the branded "string & { __brand }"
// form: the branded form would reject the literal argument to
// table()/column() and break compile-time membership validation. The union still
// makes a wrong literal fail tsc (table('nope') / column<'message'>('nope')), which
// is the spec intent. Consumers MUST build identifiers via the helpers below, never
// via "as" casts (an ESLint rule bans raw casts — wired in A1b with consumers).
export type DbTableName = (typeof DB_TABLES)[number]
export type DbColumnName<T extends DbTableName = DbTableName> = (typeof DB_COLUMNS_BY_TABLE)[T][number]['name']

export interface DbColumnEntry<T extends DbTableName = DbTableName> {
  readonly name: DbColumnName<T>
  readonly dbName: string
  readonly isPrimaryKey: boolean
  readonly isNullable: boolean
  readonly sqlType: 'text' | 'integer' | 'real' | 'blob'
}

export type PrimaryKeyKind = 'uuid-v4' | 'uuid-v7' | 'natural' | 'composite' | 'autoincrement'

export interface PrimaryKeyFact {
  readonly table: DbTableName
  readonly columns: readonly DbColumnName[]
  readonly kind: PrimaryKeyKind
  readonly ambiguous?: boolean
}

export interface ForeignKeyFact {
  readonly columns: readonly DbColumnName[]
  readonly targetTable: DbTableName
  readonly targetColumns: readonly DbColumnName[]
  readonly onDelete: 'cascade' | 'restrict' | 'set null' | 'no action' | 'set default'
}

/** A UNIQUE constraint/index as a column set (order-insensitive). */
export interface UniqueKeyFact {
  readonly columns: readonly DbColumnName[]
}

// Compile-time validation helpers. table('x')/column<'t'>('c') fail tsc when the
// literal is not a known table/column, so typos surface at compile time.
export function table<T extends DbTableName>(literal: T): T {
  return literal
}
export function column<T extends DbTableName>(literal: DbColumnName<T>): DbColumnName<T> {
  return literal
}
export function columns<T extends DbTableName>(literals: readonly DbColumnName<T>[]): readonly DbColumnName<T>[] {
  return literals
}
// Mirror a codegen PK fact for a table whose contributor knows its PK is
// unambiguous, forcing ambiguous:false (overrides the H4/H5 heuristic). The single
// shared replacement for the per-file `pk()` helper previously duplicated across
// contributors. Forward-references DB_PRIMARY_KEYS (defined below) — safe because
// mirrorPk is only ever called at contributor-module load, after this module fully
// evaluates.
export function mirrorPk(t: DbTableName): PrimaryKeyFact {
  return { ...DB_PRIMARY_KEYS[t], ambiguous: false as const }
}

// 1. Business tables discovered via sqliteTable() calls. Excludes
//    __drizzle_migrations (runtime infra, not a sqliteTable definition) and the
//    FTS virtual tables (raw CREATE VIRTUAL TABLE SQL, listed in DB_FTS_VIRTUAL_TABLES).
export const DB_TABLES = [
  'agent',
  'agent_channel',
  'agent_channel_task',
  'agent_global_skill',
  'agent_mcp_server',
  'agent_session',
  'agent_session_message',
  'agent_skill',
  'agent_workspace',
  'app_state',
  'assistant',
  'assistant_knowledge_base',
  'assistant_mcp_server',
  'chat_message_file_ref',
  'entity_tag',
  'file_entry',
  'group',
  'job',
  'job_schedule',
  'knowledge_base',
  'knowledge_item',
  'mcp_server',
  'message',
  'mini_app',
  'note',
  'painting',
  'painting_file_ref',
  'pin',
  'preference',
  'prompt',
  'tag',
  'topic',
  'translate_history',
  'translate_language',
  'user_model',
  'user_provider'
] as const

// 2. Columns per table (Drizzle declaration order, NOT re-sorted). dbName is the
//    camelCase JS property key; the physical snake_case SQLite column is derived by
//    DbService casing:'snake_case' at query time — backup uses drizzle builders only.
export const DB_COLUMNS_BY_TABLE = {
  agent: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'type', dbName: 'type', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'description', dbName: 'description', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'instructions', dbName: 'instructions', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'model', dbName: 'model', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'planModel', dbName: 'planModel', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'smallModel', dbName: 'smallModel', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'disabledTools', dbName: 'disabledTools', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'configuration', dbName: 'configuration', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'orderKey', dbName: 'orderKey', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'deletedAt', dbName: 'deletedAt', isPrimaryKey: false, isNullable: true, sqlType: 'integer' }
  ],
  agent_channel: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'type', dbName: 'type', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'agentId', dbName: 'agentId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'sessionId', dbName: 'sessionId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'workspace', dbName: 'workspace', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'config', dbName: 'config', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'isActive', dbName: 'isActive', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'activeChatIds', dbName: 'activeChatIds', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'permissionMode', dbName: 'permissionMode', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  agent_channel_task: [
    { name: 'channelId', dbName: 'channelId', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'taskId', dbName: 'taskId', isPrimaryKey: true, isNullable: false, sqlType: 'text' }
  ],
  agent_global_skill: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'description', dbName: 'description', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'folderName', dbName: 'folderName', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'source', dbName: 'source', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'sourceUrl', dbName: 'sourceUrl', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'namespace', dbName: 'namespace', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'author', dbName: 'author', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'tags', dbName: 'tags', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'contentHash', dbName: 'contentHash', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'isEnabled', dbName: 'isEnabled', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  agent_mcp_server: [
    { name: 'agentId', dbName: 'agentId', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'mcpServerId', dbName: 'mcpServerId', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  agent_session: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'agentId', dbName: 'agentId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    {
      name: 'isNameManuallyEdited',
      dbName: 'isNameManuallyEdited',
      isPrimaryKey: false,
      isNullable: false,
      sqlType: 'integer'
    },
    { name: 'description', dbName: 'description', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'workspaceId', dbName: 'workspaceId', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'traceId', dbName: 'traceId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'orderKey', dbName: 'orderKey', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  agent_session_message: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'sessionId', dbName: 'sessionId', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'role', dbName: 'role', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'data', dbName: 'data', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'searchableText', dbName: 'searchableText', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'status', dbName: 'status', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'modelId', dbName: 'modelId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'modelSnapshot', dbName: 'modelSnapshot', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'stats', dbName: 'stats', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    {
      name: 'runtimeResumeToken',
      dbName: 'runtimeResumeToken',
      isPrimaryKey: false,
      isNullable: true,
      sqlType: 'text'
    },
    { name: 'ftsRowid', dbName: 'ftsRowid', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  agent_skill: [
    { name: 'agentId', dbName: 'agentId', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'skillId', dbName: 'skillId', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'isEnabled', dbName: 'isEnabled', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  agent_workspace: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'path', dbName: 'path', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'type', dbName: 'type', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'orderKey', dbName: 'orderKey', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  app_state: [
    { name: 'key', dbName: 'key', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'value', dbName: 'value', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'description', dbName: 'description', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  assistant: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'prompt', dbName: 'prompt', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'emoji', dbName: 'emoji', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'description', dbName: 'description', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'modelId', dbName: 'modelId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'settings', dbName: 'settings', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'orderKey', dbName: 'orderKey', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'deletedAt', dbName: 'deletedAt', isPrimaryKey: false, isNullable: true, sqlType: 'integer' }
  ],
  assistant_knowledge_base: [
    { name: 'assistantId', dbName: 'assistantId', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'knowledgeBaseId', dbName: 'knowledgeBaseId', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  assistant_mcp_server: [
    { name: 'assistantId', dbName: 'assistantId', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'mcpServerId', dbName: 'mcpServerId', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  chat_message_file_ref: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'fileEntryId', dbName: 'fileEntryId', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'sourceId', dbName: 'sourceId', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'role', dbName: 'role', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  entity_tag: [
    { name: 'entityType', dbName: 'entityType', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'entityId', dbName: 'entityId', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'tagId', dbName: 'tagId', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  file_entry: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'origin', dbName: 'origin', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'ext', dbName: 'ext', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'size', dbName: 'size', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'externalPath', dbName: 'externalPath', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'deletedAt', dbName: 'deletedAt', isPrimaryKey: false, isNullable: true, sqlType: 'integer' }
  ],
  group: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'entityType', dbName: 'entityType', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'orderKey', dbName: 'orderKey', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  job: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'type', dbName: 'type', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'status', dbName: 'status', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'priority', dbName: 'priority', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'queue', dbName: 'queue', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'idempotencyKey', dbName: 'idempotencyKey', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'scheduleId', dbName: 'scheduleId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'scheduledAt', dbName: 'scheduledAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'startedAt', dbName: 'startedAt', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'finishedAt', dbName: 'finishedAt', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'attempt', dbName: 'attempt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'maxAttempts', dbName: 'maxAttempts', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'input', dbName: 'input', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'output', dbName: 'output', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'error', dbName: 'error', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'parentId', dbName: 'parentId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'cancelRequested', dbName: 'cancelRequested', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'metadata', dbName: 'metadata', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'timeoutMs', dbName: 'timeoutMs', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  job_schedule: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'type', dbName: 'type', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'trigger', dbName: 'trigger', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'jobInputTemplate', dbName: 'jobInputTemplate', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'enabled', dbName: 'enabled', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'nextRun', dbName: 'nextRun', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'lastRun', dbName: 'lastRun', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'catchUpPolicy', dbName: 'catchUpPolicy', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'metadata', dbName: 'metadata', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  knowledge_base: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'groupId', dbName: 'groupId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'dimensions', dbName: 'dimensions', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'embeddingModelId', dbName: 'embeddingModelId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'status', dbName: 'status', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'error', dbName: 'error', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'rerankModelId', dbName: 'rerankModelId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'fileProcessorId', dbName: 'fileProcessorId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'chunkSize', dbName: 'chunkSize', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'chunkOverlap', dbName: 'chunkOverlap', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'chunkStrategy', dbName: 'chunkStrategy', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'chunkSeparator', dbName: 'chunkSeparator', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'threshold', dbName: 'threshold', isPrimaryKey: false, isNullable: true, sqlType: 'real' },
    { name: 'documentCount', dbName: 'documentCount', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  knowledge_item: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'baseId', dbName: 'baseId', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'groupId', dbName: 'groupId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'type', dbName: 'type', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'data', dbName: 'data', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'status', dbName: 'status', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'error', dbName: 'error', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  mcp_server: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'type', dbName: 'type', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'description', dbName: 'description', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'baseUrl', dbName: 'baseUrl', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'command', dbName: 'command', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'registryUrl', dbName: 'registryUrl', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'args', dbName: 'args', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'env', dbName: 'env', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'headers', dbName: 'headers', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'provider', dbName: 'provider', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'providerUrl', dbName: 'providerUrl', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'logoUrl', dbName: 'logoUrl', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'tags', dbName: 'tags', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'longRunning', dbName: 'longRunning', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'timeout', dbName: 'timeout', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'dxtVersion', dbName: 'dxtVersion', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'dxtPath', dbName: 'dxtPath', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'reference', dbName: 'reference', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'searchKey', dbName: 'searchKey', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'configSample', dbName: 'configSample', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'disabledTools', dbName: 'disabledTools', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    {
      name: 'disabledAutoApproveTools',
      dbName: 'disabledAutoApproveTools',
      isPrimaryKey: false,
      isNullable: true,
      sqlType: 'text'
    },
    { name: 'shouldConfig', dbName: 'shouldConfig', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'sortOrder', dbName: 'sortOrder', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'isActive', dbName: 'isActive', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'installSource', dbName: 'installSource', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'isTrusted', dbName: 'isTrusted', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'trustedAt', dbName: 'trustedAt', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'installedAt', dbName: 'installedAt', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  message: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'parentId', dbName: 'parentId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'topicId', dbName: 'topicId', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'role', dbName: 'role', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'data', dbName: 'data', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'searchableText', dbName: 'searchableText', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'status', dbName: 'status', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'siblingsGroupId', dbName: 'siblingsGroupId', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'modelId', dbName: 'modelId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'modelSnapshot', dbName: 'modelSnapshot', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'stats', dbName: 'stats', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'ftsRowid', dbName: 'ftsRowid', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'deletedAt', dbName: 'deletedAt', isPrimaryKey: false, isNullable: true, sqlType: 'integer' }
  ],
  mini_app: [
    { name: 'appId', dbName: 'appId', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'presetMiniAppId', dbName: 'presetMiniAppId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'url', dbName: 'url', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'logo', dbName: 'logo', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'status', dbName: 'status', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'orderKey', dbName: 'orderKey', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'bordered', dbName: 'bordered', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'background', dbName: 'background', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'supportedRegions', dbName: 'supportedRegions', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'configuration', dbName: 'configuration', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'nameKey', dbName: 'nameKey', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  note: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'rootPath', dbName: 'rootPath', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'path', dbName: 'path', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'isStarred', dbName: 'isStarred', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'isExpanded', dbName: 'isExpanded', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  painting: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'providerId', dbName: 'providerId', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'modelId', dbName: 'modelId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'prompt', dbName: 'prompt', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'orderKey', dbName: 'orderKey', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  painting_file_ref: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'fileEntryId', dbName: 'fileEntryId', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'sourceId', dbName: 'sourceId', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'role', dbName: 'role', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  pin: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'entityType', dbName: 'entityType', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'entityId', dbName: 'entityId', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'orderKey', dbName: 'orderKey', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  preference: [
    { name: 'scope', dbName: 'scope', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'key', dbName: 'key', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'value', dbName: 'value', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  prompt: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'title', dbName: 'title', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'content', dbName: 'content', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'orderKey', dbName: 'orderKey', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  tag: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'color', dbName: 'color', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  topic: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    {
      name: 'isNameManuallyEdited',
      dbName: 'isNameManuallyEdited',
      isPrimaryKey: false,
      isNullable: false,
      sqlType: 'integer'
    },
    { name: 'assistantId', dbName: 'assistantId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'activeNodeId', dbName: 'activeNodeId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'groupId', dbName: 'groupId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'traceId', dbName: 'traceId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'orderKey', dbName: 'orderKey', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'deletedAt', dbName: 'deletedAt', isPrimaryKey: false, isNullable: true, sqlType: 'integer' }
  ],
  translate_history: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'sourceText', dbName: 'sourceText', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'targetText', dbName: 'targetText', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'sourceLanguage', dbName: 'sourceLanguage', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'targetLanguage', dbName: 'targetLanguage', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'star', dbName: 'star', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  translate_language: [
    { name: 'langCode', dbName: 'langCode', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'value', dbName: 'value', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'emoji', dbName: 'emoji', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  user_model: [
    { name: 'id', dbName: 'id', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'providerId', dbName: 'providerId', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'modelId', dbName: 'modelId', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'presetModelId', dbName: 'presetModelId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'description', dbName: 'description', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'group', dbName: 'group', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'capabilities', dbName: 'capabilities', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'inputModalities', dbName: 'inputModalities', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'outputModalities', dbName: 'outputModalities', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'endpointTypes', dbName: 'endpointTypes', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'customEndpointUrl', dbName: 'customEndpointUrl', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'contextWindow', dbName: 'contextWindow', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'maxInputTokens', dbName: 'maxInputTokens', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    { name: 'maxOutputTokens', dbName: 'maxOutputTokens', isPrimaryKey: false, isNullable: true, sqlType: 'integer' },
    {
      name: 'supportsStreaming',
      dbName: 'supportsStreaming',
      isPrimaryKey: false,
      isNullable: false,
      sqlType: 'integer'
    },
    { name: 'reasoning', dbName: 'reasoning', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'parameters', dbName: 'parameters', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'pricing', dbName: 'pricing', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'isEnabled', dbName: 'isEnabled', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'isHidden', dbName: 'isHidden', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'isDeprecated', dbName: 'isDeprecated', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'orderKey', dbName: 'orderKey', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'notes', dbName: 'notes', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'userOverrides', dbName: 'userOverrides', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ],
  user_provider: [
    { name: 'providerId', dbName: 'providerId', isPrimaryKey: true, isNullable: false, sqlType: 'text' },
    { name: 'presetProviderId', dbName: 'presetProviderId', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'name', dbName: 'name', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'endpointConfigs', dbName: 'endpointConfigs', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    {
      name: 'defaultChatEndpoint',
      dbName: 'defaultChatEndpoint',
      isPrimaryKey: false,
      isNullable: true,
      sqlType: 'text'
    },
    { name: 'apiKeys', dbName: 'apiKeys', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'authConfig', dbName: 'authConfig', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'apiFeatures', dbName: 'apiFeatures', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'providerSettings', dbName: 'providerSettings', isPrimaryKey: false, isNullable: true, sqlType: 'text' },
    { name: 'isEnabled', dbName: 'isEnabled', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'orderKey', dbName: 'orderKey', isPrimaryKey: false, isNullable: false, sqlType: 'text' },
    { name: 'createdAt', dbName: 'createdAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' },
    { name: 'updatedAt', dbName: 'updatedAt', isPrimaryKey: false, isNullable: false, sqlType: 'integer' }
  ]
} as const satisfies {
  readonly [T in DbTableName]: readonly {
    readonly name: string
    readonly dbName: string
    readonly isPrimaryKey: boolean
    readonly isNullable: boolean
    readonly sqlType: 'text' | 'integer' | 'real' | 'blob'
  }[]
}

// 3. Primary-key facts (keys dict-ascending). ambiguous:true means a contributor
//    MUST override this PK explicitly (H4/H5 heuristic).
export const DB_PRIMARY_KEYS = {
  agent: { table: 'agent', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  agent_channel: { table: 'agent_channel', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  agent_channel_task: {
    table: 'agent_channel_task',
    columns: ['channelId', 'taskId'],
    kind: 'composite',
    ambiguous: false
  },
  agent_global_skill: { table: 'agent_global_skill', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  agent_mcp_server: {
    table: 'agent_mcp_server',
    columns: ['agentId', 'mcpServerId'],
    kind: 'composite',
    ambiguous: false
  },
  agent_session: { table: 'agent_session', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  agent_session_message: { table: 'agent_session_message', columns: ['id'], kind: 'uuid-v7', ambiguous: false },
  agent_skill: { table: 'agent_skill', columns: ['agentId', 'skillId'], kind: 'composite', ambiguous: false },
  agent_workspace: { table: 'agent_workspace', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  app_state: { table: 'app_state', columns: ['key'], kind: 'natural', ambiguous: true },
  assistant: { table: 'assistant', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  assistant_knowledge_base: {
    table: 'assistant_knowledge_base',
    columns: ['assistantId', 'knowledgeBaseId'],
    kind: 'composite',
    ambiguous: false
  },
  assistant_mcp_server: {
    table: 'assistant_mcp_server',
    columns: ['assistantId', 'mcpServerId'],
    kind: 'composite',
    ambiguous: false
  },
  chat_message_file_ref: { table: 'chat_message_file_ref', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  entity_tag: {
    table: 'entity_tag',
    columns: ['entityType', 'entityId', 'tagId'],
    kind: 'composite',
    ambiguous: false
  },
  file_entry: { table: 'file_entry', columns: ['id'], kind: 'uuid-v7', ambiguous: false },
  group: { table: 'group', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  job: { table: 'job', columns: ['id'], kind: 'uuid-v7', ambiguous: false },
  job_schedule: { table: 'job_schedule', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  knowledge_base: { table: 'knowledge_base', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  knowledge_item: { table: 'knowledge_item', columns: ['id'], kind: 'uuid-v7', ambiguous: false },
  mcp_server: { table: 'mcp_server', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  message: { table: 'message', columns: ['id'], kind: 'uuid-v7', ambiguous: false },
  mini_app: { table: 'mini_app', columns: ['appId'], kind: 'natural', ambiguous: true },
  note: { table: 'note', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  painting: { table: 'painting', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  painting_file_ref: { table: 'painting_file_ref', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  pin: { table: 'pin', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  preference: { table: 'preference', columns: ['scope', 'key'], kind: 'composite', ambiguous: false },
  prompt: { table: 'prompt', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  tag: { table: 'tag', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  topic: { table: 'topic', columns: ['id'], kind: 'uuid-v4', ambiguous: false },
  translate_history: { table: 'translate_history', columns: ['id'], kind: 'uuid-v7', ambiguous: false },
  translate_language: { table: 'translate_language', columns: ['langCode'], kind: 'natural', ambiguous: true },
  user_model: { table: 'user_model', columns: ['id'], kind: 'natural', ambiguous: true },
  user_provider: { table: 'user_provider', columns: ['providerId'], kind: 'natural', ambiguous: true }
} as const satisfies Readonly<Record<DbTableName, PrimaryKeyFact>>

// 3b. Foreign-key facts — the single source of truth for onDelete policy,
//     consumed by finalize #19 (ReferenceKind vs onDelete) and #24 (every declared
//     EntityReference must match a generated FK). onDelete is normalized: a schema
//     FK without ON DELETE yields 'no action' (SQLite default), never undefined.
export const DB_FOREIGN_KEYS = {
  agent: [
    { columns: ['model'], targetTable: 'user_model', targetColumns: ['id'], onDelete: 'set null' },
    { columns: ['planModel'], targetTable: 'user_model', targetColumns: ['id'], onDelete: 'set null' },
    { columns: ['smallModel'], targetTable: 'user_model', targetColumns: ['id'], onDelete: 'set null' }
  ],
  agent_channel: [
    { columns: ['agentId'], targetTable: 'agent', targetColumns: ['id'], onDelete: 'set null' },
    { columns: ['sessionId'], targetTable: 'agent_session', targetColumns: ['id'], onDelete: 'set null' }
  ],
  agent_channel_task: [
    { columns: ['channelId'], targetTable: 'agent_channel', targetColumns: ['id'], onDelete: 'cascade' },
    { columns: ['taskId'], targetTable: 'job_schedule', targetColumns: ['id'], onDelete: 'cascade' }
  ],
  agent_global_skill: [],
  agent_mcp_server: [
    { columns: ['agentId'], targetTable: 'agent', targetColumns: ['id'], onDelete: 'cascade' },
    { columns: ['mcpServerId'], targetTable: 'mcp_server', targetColumns: ['id'], onDelete: 'cascade' }
  ],
  agent_session: [
    { columns: ['agentId'], targetTable: 'agent', targetColumns: ['id'], onDelete: 'set null' },
    { columns: ['workspaceId'], targetTable: 'agent_workspace', targetColumns: ['id'], onDelete: 'cascade' }
  ],
  agent_session_message: [
    { columns: ['sessionId'], targetTable: 'agent_session', targetColumns: ['id'], onDelete: 'cascade' },
    { columns: ['modelId'], targetTable: 'user_model', targetColumns: ['id'], onDelete: 'set null' }
  ],
  agent_skill: [
    { columns: ['agentId'], targetTable: 'agent', targetColumns: ['id'], onDelete: 'cascade' },
    { columns: ['skillId'], targetTable: 'agent_global_skill', targetColumns: ['id'], onDelete: 'cascade' }
  ],
  agent_workspace: [],
  app_state: [],
  assistant: [{ columns: ['modelId'], targetTable: 'user_model', targetColumns: ['id'], onDelete: 'set null' }],
  assistant_knowledge_base: [
    { columns: ['assistantId'], targetTable: 'assistant', targetColumns: ['id'], onDelete: 'cascade' },
    { columns: ['knowledgeBaseId'], targetTable: 'knowledge_base', targetColumns: ['id'], onDelete: 'cascade' }
  ],
  assistant_mcp_server: [
    { columns: ['assistantId'], targetTable: 'assistant', targetColumns: ['id'], onDelete: 'cascade' },
    { columns: ['mcpServerId'], targetTable: 'mcp_server', targetColumns: ['id'], onDelete: 'cascade' }
  ],
  chat_message_file_ref: [
    { columns: ['fileEntryId'], targetTable: 'file_entry', targetColumns: ['id'], onDelete: 'cascade' },
    { columns: ['sourceId'], targetTable: 'message', targetColumns: ['id'], onDelete: 'cascade' }
  ],
  entity_tag: [{ columns: ['tagId'], targetTable: 'tag', targetColumns: ['id'], onDelete: 'cascade' }],
  file_entry: [],
  group: [],
  job: [
    { columns: ['scheduleId'], targetTable: 'job_schedule', targetColumns: ['id'], onDelete: 'set null' },
    { columns: ['parentId'], targetTable: 'job', targetColumns: ['id'], onDelete: 'set null' }
  ],
  job_schedule: [],
  knowledge_base: [
    { columns: ['groupId'], targetTable: 'group', targetColumns: ['id'], onDelete: 'set null' },
    { columns: ['embeddingModelId'], targetTable: 'user_model', targetColumns: ['id'], onDelete: 'no action' },
    { columns: ['rerankModelId'], targetTable: 'user_model', targetColumns: ['id'], onDelete: 'set null' }
  ],
  knowledge_item: [
    { columns: ['baseId'], targetTable: 'knowledge_base', targetColumns: ['id'], onDelete: 'cascade' },
    {
      columns: ['baseId', 'groupId'],
      targetTable: 'knowledge_item',
      targetColumns: ['baseId', 'id'],
      onDelete: 'cascade'
    }
  ],
  mcp_server: [],
  message: [
    { columns: ['topicId'], targetTable: 'topic', targetColumns: ['id'], onDelete: 'cascade' },
    { columns: ['modelId'], targetTable: 'user_model', targetColumns: ['id'], onDelete: 'set null' },
    { columns: ['parentId'], targetTable: 'message', targetColumns: ['id'], onDelete: 'cascade' }
  ],
  mini_app: [],
  note: [],
  painting: [],
  painting_file_ref: [
    { columns: ['fileEntryId'], targetTable: 'file_entry', targetColumns: ['id'], onDelete: 'cascade' },
    { columns: ['sourceId'], targetTable: 'painting', targetColumns: ['id'], onDelete: 'cascade' }
  ],
  pin: [],
  preference: [],
  prompt: [],
  tag: [],
  topic: [
    { columns: ['assistantId'], targetTable: 'assistant', targetColumns: ['id'], onDelete: 'set null' },
    { columns: ['groupId'], targetTable: 'group', targetColumns: ['id'], onDelete: 'set null' }
  ],
  translate_history: [
    {
      columns: ['sourceLanguage'],
      targetTable: 'translate_language',
      targetColumns: ['langCode'],
      onDelete: 'set null'
    },
    {
      columns: ['targetLanguage'],
      targetTable: 'translate_language',
      targetColumns: ['langCode'],
      onDelete: 'set null'
    }
  ],
  translate_language: [],
  user_model: [
    { columns: ['providerId'], targetTable: 'user_provider', targetColumns: ['providerId'], onDelete: 'cascade' }
  ],
  user_provider: []
} as const satisfies Readonly<Record<DbTableName, readonly ForeignKeyFact[]>>

// 3c. Unique-key facts — every UNIQUE constraint/index, as column sets, so finalize
//     #13 can verify a natural-key aggregate's identityKey is genuinely unique
//     (cross-device identity). Aggregates three schema sources: uniqueIndex(),
//     table-level unique().on(...), and inline column .unique() (the last is
//     invisible to the first two — only column.isUnique exposes it). Partial unique
//     indexes (WHERE) are excluded — not a cross-device identity guarantee. FTS5
//     sync columns (message/agent_session_message ftsRowid) DO appear here but are
//     NOT business-identity candidates — #13 only consults this map for non-PK
//     natural keys, and these tables are uuid-entity (identityKey = PK id), so
//     ftsRowid never reaches the identity check.
export const DB_UNIQUE_KEYS = {
  agent: [],
  agent_channel: [],
  agent_channel_task: [],
  agent_global_skill: [{ columns: ['folderName'] }],
  agent_mcp_server: [],
  agent_session: [],
  agent_session_message: [{ columns: ['ftsRowid'] }],
  agent_skill: [],
  agent_workspace: [{ columns: ['path'] }],
  app_state: [],
  assistant: [],
  assistant_knowledge_base: [],
  assistant_mcp_server: [],
  chat_message_file_ref: [{ columns: ['fileEntryId', 'sourceId', 'role'] }],
  entity_tag: [],
  file_entry: [],
  group: [],
  job: [],
  job_schedule: [{ columns: ['type', 'name'] }],
  knowledge_base: [],
  knowledge_item: [{ columns: ['baseId', 'id'] }],
  mcp_server: [],
  message: [{ columns: ['ftsRowid'] }],
  mini_app: [],
  note: [{ columns: ['rootPath', 'path'] }],
  painting: [],
  painting_file_ref: [{ columns: ['fileEntryId', 'sourceId', 'role'] }],
  pin: [{ columns: ['entityType', 'entityId'] }],
  preference: [],
  prompt: [],
  tag: [{ columns: ['name'] }],
  topic: [],
  translate_history: [],
  translate_language: [],
  user_model: [{ columns: ['providerId', 'modelId'] }],
  user_provider: []
} as const satisfies Readonly<Record<DbTableName, readonly UniqueKeyFact[]>>

// 3d. FTS5 virtual tables (content-table mapping). Keys are the FTS virtual table
//     names (not in DB_TABLES, in ALWAYS_STRIP); values are content tables (in
//     DB_TABLES). Parsed from the *_FTS_STATEMENTS content= clauses.
export const DB_FTS_VIRTUAL_TABLES = {
  agent_session_message_fts: 'agent_session_message',
  message_fts: 'message'
} as const satisfies Readonly<Record<string, DbTableName>>

// 5. Generation metadata for diagnostics. Excluded from byte-for-byte CHECK.
export const BACKUP_REFS_META = {
  generatedAt: '2026-07-09T08:54:11.163Z'
} as const
